### ISSUE TITLE
Persona will be shutdown :(

### ISSUE THREAD

**Issue by xeor** [wrr/wwwhisper#19]
Persona will turn off the 30th of November, see https://developer.mozilla.org/en-US/Persona

There are a lot of information @ https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers and the source is available @ https://github.com/mozilla/persona

If Mozilla is shutting the service down, the state of the opensource project should also be considered. Will it die out? Maybe it is better to replace the login logic with something more generic? Maybe `python social auth` is the way to go (http://psa.matiasaguirre.net/)?

**Comment by wrr** [comment]
During the next few months wwwhisper will migrate away from Persona. It will most likely switch to email based authentication tokens (similar to https://passwordless.net/). Because such tokens still use emails for identity, the switch should be painless for users (current wwwhisper access control rules will continue working).

This switch should also solve some usability problems with Persona pop-up window, the pop-up will no longer be needed. It will also enable wwwhisper to work on IOS devices, where Persona pop-up was blocked.

The downside of the switch is that wwwhisper back-end will need to be configured to send emails with tokens. Sending emails from a web back-end is in general non-trivial (often a third party email delivery service is used to ensure reliable delivery).

**Comment by lumshod** [comment]
:+1: to something like passwordless

**Comment by xeor** [comment]
Have there been any more thoughts on this? :)

**Comment by michaeltrollan** [comment]
Seconded -- any progress?

**Comment by wrr** [comment]
The switch will be finished by the end of August. Server side functionality is already done, but UI still needs to be updated. Thank you for your patience.

**Comment by wrr** [comment]
wwwhisper Heroku add-on is already switched to the token based authentication. 

Setup scripts and documentation for wwwhisper standalone still need to be updated. For token based authentication wwwhisper backend is sending emails, so it needs to allow for some generic configuration of email delivery backend.
